# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AdmostTestSuite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking', '~> 4.0'

  # Pods for AdmostTestSuite

  target 'AdmostTestSuiteTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'AdmostTestSuiteUITests' do
    # Pods for testing
  end

end
